From ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y iputils-ping -y
RUN apt-get install -y lynx
RUN apt-get install -y mutt
RUN apt-get install -y dnsutils


